<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="FYNXTLAPIND066" failures="3" tests="7" name="Test" time="218.823" errors="0" timestamp="2024-09-26T14:46:25 IST">
  <testcase classname="testCases.TC001_ValidLoginTest" name="verify_login" time="7.436"/>
  <testcase classname="testCases.TC002_InValidLoginTest" name="verify_login_Error" time="8.538"/>
  <testcase classname="testCases.TC003_AccountRegistrationTest" name="account_registration" time="10.762"/>
  <testcase classname="testCases.TC004_CreateMT4AccountTest" name="createMT4_Account" time="32.828">
    <failure type="java.lang.AssertionError" message="Test failed due to an exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to an exception.
at testCases.TC004_CreateMT4AccountTest.createMT4_Account(TC004_CreateMT4AccountTest.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- createMT4_Account -->
  <testcase classname="testCases.TC005_DepositFundsUSDTest" name="depositFundsUSD" time="23.348"/>
  <testcase classname="testCases.TC005_DepositFundsUSDTest" name="approvedepositFundsUSD" time="21.389">
    <failure type="java.lang.AssertionError" message="Test failed due to an exception: no such element: Unable to locate element: {&amp;quot;method&amp;quot;:&amp;quot;xpath&amp;quot;,&amp;quot;selector&amp;quot;:&amp;quot;//i[@data-dismiss=&amp;apos;modal&amp;apos;]&amp;quot;}
  (Session info: chrome=129.0.6668.70)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: &amp;apos;4.23.1&amp;apos;, revision: &amp;apos;656257d8e9&amp;apos;
System info: os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;21.0.4&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [1b9dc83301e6369e1ab999e79bc21200, findElement {using=xpath, value=//i[@data-dismiss=&amp;apos;modal&amp;apos;]}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.70, chrome: {chromedriverVersion: 129.0.6668.70 (df87d5cf12b1..., userDataDir: C:\Users\ABDULS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:65504}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:65504/devtoo..., se:cdpVersion: 129.0.6668.70, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 1b9dc83301e6369e1ab999e79bc21200">
      <![CDATA[java.lang.AssertionError: Test failed due to an exception: no such element: Unable to locate element: {"method":"xpath","selector":"//i[@data-dismiss='modal']"}
  (Session info: chrome=129.0.6668.70)
For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Build info: version: '4.23.1', revision: '656257d8e9'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.4'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [1b9dc83301e6369e1ab999e79bc21200, findElement {using=xpath, value=//i[@data-dismiss='modal']}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 129.0.6668.70, chrome: {chromedriverVersion: 129.0.6668.70 (df87d5cf12b1..., userDataDir: C:\Users\ABDULS~1\AppData\L...}, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:65504}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: windows, proxy: Proxy(), se:cdp: ws://localhost:65504/devtoo..., se:cdpVersion: 129.0.6668.70, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 1b9dc83301e6369e1ab999e79bc21200
at testCases.TC005_DepositFundsUSDTest.approvedepositFundsUSD(TC005_DepositFundsUSDTest.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- approvedepositFundsUSD -->
  <testcase classname="testCases.TC015_CreatePublicStrategy" name="create_Public_strategy" time="34.944">
    <failure type="java.lang.AssertionError" message="Test failed due to an exception.">
      <![CDATA[java.lang.AssertionError: Test failed due to an exception.
at testCases.TC015_CreatePublicStrategy.create_Public_strategy(TC015_CreatePublicStrategy.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- create_Public_strategy -->
</testsuite> <!-- Test -->
